module.exports = {
  apps: [
    {
      name: "Sniper Pancake ID=0",
      script: "./process_id_0.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=1",
      script: "./process_id_1.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=2",
      script: "./process_id_2.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=3",
      script: "./process_id_3.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=4",
      script: "./process_id_4.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=5",
      script: "./process_id_5.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=6",
      script: "./process_id_6.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=7",
      script: "./process_id_7.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "Sniper Pancake ID=8",
      script: "./process_id_8.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    // Các tệp JavaScript khác có thể được thêm vào đây
  ],
};
